### ISSUE TITLE
Fill out the Readme

### ISSUE THREAD

**Issue by isEvrythngTkn** [ChrisCoastal/modenki#2]
In order for me to understand this repo and review it, I need to know how to work with it. A readme would make a big difference!

There are lots of readme templates out there, and they all follow a similar format. Give it a try!

https://github.com/othneildrew/Best-README-Template

**Comment by ChrisCoastal** [comment]
Hey @isEvrythngTkn thanks for opening this issue and helpful suggestion! You're right it will make an essential improvement.

**Comment by ChrisCoastal** [comment]
Hi @isEvrythngTkn, I've taken a first run at improving the readme, with the resource you provided, on the responsive branch [https://github.com/ChrisCoastal/modenki/tree/responsive](url). If you have a free moment, please take a look and let me know if there is anything critical it is missing.
