### ISSUE TITLE
Menu disappears on larger resolutions

### ISSUE THREAD

**Issue by isEvrythngTkn** [ChrisCoastal/modenki#3]
When I make my screen big, the menu disappears.

![missing_menu](https://user-images.githubusercontent.com/32043224/160892603-b74624b7-72c2-4f20-afe7-e5f982110bbe.png)

**Comment by ChrisCoastal** [comment]
Thanks for catching and reporting this issue. 🙏  Looks like it came from a gap in the nav bar media queries. 💡
